# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: make-cookiecutter-and-test-installer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  make-cookiecutter-and-test-installer:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Add poetry
      uses: abatilo/actions-poetry@v2
    - name: Install pip and cookiecutter to global
      run: |
        python -m pip install --upgrade pip
        pip install cookiecutter
    - name: Run cookiecutter
      run: cookiecutter . --no-input -o ~
    - name: Build dummy package  
      run: cd ~/my-lovely-project && poetry build
    - name: Run install script without requirements.txt
      run: cd ~/my-lovely-project/dist && ./install_on_linux.sh
    - name: Create requirements.txt
      run: cd ~/my-lovely-project && poetry export -f requirements.txt --output dist/requirements.txt
    - name: Delete previous installation
      run: rm -r /opt/my-lovely-project
    - name: Run install script with requirements.txt
      run: cd ~/my-lovely-project/dist && ./install_on_linux.sh
    - name: Run executable
      run: cd /opt/my-lovely-project && ./my-lovely-project
    - name: Delete the env
      run: rm -r /opt/my-lovely-project/env
    - name: Run refresh script
      run:  cd /opt/my-lovely-project/bin/ && ./refresh-my-lovely-project.sh
    - name: Run executable
      run: cd /opt/my-lovely-project && ./my-lovely-project

  make-cookiecutter-and-test-installer-win:

    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Add poetry
      uses: abatilo/actions-poetry@v2
    - name: Install pip and cookiecutter to global
      run: |
        python -m pip install --upgrade pip
        pip install cookiecutter
    - name: Make source dir
      run: mkdir \source
    - name: Run cookiecutter
      run: cookiecutter . --no-input -o \source
    - name: Build dummy package
      run: cd \source\my-lovely-project && poetry build
    - name: Run install script without requirements.txt
      run: "cd \\source\\my-lovely-project\\dist && install_on_windows.cmd D:"
    - name: Create requirements.txt
      run: cd \source\my-lovely-project && poetry export -f requirements.txt --output dist\requirements.txt
    - name: Delete previous installation
      run: rm -r \my-lovely-project
    - name: Run install script with requirements.txt
      run: "cd \\source\\my-lovely-project\\dist && install_on_windows.cmd D:"
    - name: Run executable
      run: cd \my-lovely-project && my-lovely-project.exe
    - name: Delete the env
      run: rm -r \my-lovely-project\env
    - name: Run refresh script
      run: \my-lovely-project\bin\refresh-my-lovely-project.cmd
    - name: Run executable
      run: cd \my-lovely-project && my-lovely-project.exe
